/*
 * generated by Xtext
 */
package org.yazgel.regex.s2m;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class S2MUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.yazgel.regex.s2m.ui.internal.S2MActivator.getInstance().getInjector("org.yazgel.regex.s2m.S2M");
	}
	
}
