/*
 * generated by Xtext
 */
package org.yazgel.regex.s2m.generator;

public class S2MRunner {
	
	private static S2MRunner instance = null;
	
	private S2MRunner() {
	}

	public static S2MRunner getInstance() {
		if (instance == null) {
			instance = new S2MRunner();
		}
		return instance;
	 }
	
	public Object run(String fileUri, String content){
		String[] myStrings = { fileUri, content};
		Main.main(myStrings); 
		return Main.getResult();
	}
}
