/*
 * generated by Xtext
 */
package org.yazgel.regex.s2m.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.yazgel.regex.s2m.ui.internal.S2MActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class S2MExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return S2MActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return S2MActivator.getInstance().getInjector(S2MActivator.ORG_YAZGEL_REGEX_S2M_S2M);
	}
	
}
