/*
 * generated by Xtext
 */
package org.yazgel.regex.s2m.serializer;

import com.google.inject.Inject;
import com.google.inject.Provider;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticNodeProvider.INodesForEObjectProvider;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.yazgel.regex.s2m.s2M.Attribute;
import org.yazgel.regex.s2m.s2M.Model;
import org.yazgel.regex.s2m.s2M.RuleIndex;
import org.yazgel.regex.s2m.s2M.RuleIndexToKeyword;
import org.yazgel.regex.s2m.s2M.RuleKeyword;
import org.yazgel.regex.s2m.s2M.RuleKeywordToIndex;
import org.yazgel.regex.s2m.s2M.S2MPackage;
import org.yazgel.regex.s2m.services.S2MGrammarAccess;

@SuppressWarnings("all")
public class S2MSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private S2MGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == S2MPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case S2MPackage.ATTRIBUTE:
				sequence_Attribute(context, (Attribute) semanticObject); 
				return; 
			case S2MPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case S2MPackage.RULE_INDEX:
				sequence_RuleIndex(context, (RuleIndex) semanticObject); 
				return; 
			case S2MPackage.RULE_INDEX_TO_KEYWORD:
				sequence_RuleIndexToKeyword(context, (RuleIndexToKeyword) semanticObject); 
				return; 
			case S2MPackage.RULE_KEYWORD:
				sequence_RuleKeyword(context, (RuleKeyword) semanticObject); 
				return; 
			case S2MPackage.RULE_KEYWORD_TO_INDEX:
				sequence_RuleKeywordToIndex(context, (RuleKeywordToIndex) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     (name=ID type=AttributeType)
	 */
	protected void sequence_Attribute(EObject context, Attribute semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.ATTRIBUTE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.ATTRIBUTE__NAME));
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.ATTRIBUTE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.ATTRIBUTE__TYPE));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getAttributeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getAttributeAccess().getTypeAttributeTypeEnumRuleCall_5_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID attributes+=Attribute* rules+=Rule*)
	 */
	protected void sequence_Model(EObject context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID startIndex=INT endDelimeter=STRING attr=[Attribute|ID])
	 */
	protected void sequence_RuleIndexToKeyword(EObject context, RuleIndexToKeyword semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE__NAME));
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE__ATTR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE__ATTR));
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE_INDEX_TO_KEYWORD__START_INDEX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE_INDEX_TO_KEYWORD__START_INDEX));
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE_INDEX_TO_KEYWORD__END_DELIMETER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE_INDEX_TO_KEYWORD__END_DELIMETER));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getRuleIndexToKeywordAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getRuleIndexToKeywordAccess().getStartIndexINTTerminalRuleCall_3_1_0(), semanticObject.getStartIndex());
		feeder.accept(grammarAccess.getRuleIndexToKeywordAccess().getEndDelimeterSTRINGTerminalRuleCall_4_1_0(), semanticObject.getEndDelimeter());
		feeder.accept(grammarAccess.getRuleIndexToKeywordAccess().getAttrAttributeIDTerminalRuleCall_7_0_1(), semanticObject.getAttr());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID startIndex=INT endIndex=INT attr=[Attribute|ID])
	 */
	protected void sequence_RuleIndex(EObject context, RuleIndex semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE__NAME));
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE__ATTR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE__ATTR));
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE_INDEX__START_INDEX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE_INDEX__START_INDEX));
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE_INDEX__END_INDEX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE_INDEX__END_INDEX));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getRuleIndexAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getRuleIndexAccess().getStartIndexINTTerminalRuleCall_3_1_0(), semanticObject.getStartIndex());
		feeder.accept(grammarAccess.getRuleIndexAccess().getEndIndexINTTerminalRuleCall_4_1_0(), semanticObject.getEndIndex());
		feeder.accept(grammarAccess.getRuleIndexAccess().getAttrAttributeIDTerminalRuleCall_7_0_1(), semanticObject.getAttr());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID startDelimeter=STRING endIndex=INT attr=[Attribute|ID])
	 */
	protected void sequence_RuleKeywordToIndex(EObject context, RuleKeywordToIndex semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE__NAME));
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE__ATTR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE__ATTR));
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE_KEYWORD_TO_INDEX__START_DELIMETER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE_KEYWORD_TO_INDEX__START_DELIMETER));
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE_KEYWORD_TO_INDEX__END_INDEX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE_KEYWORD_TO_INDEX__END_INDEX));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getRuleKeywordToIndexAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getRuleKeywordToIndexAccess().getStartDelimeterSTRINGTerminalRuleCall_3_1_0(), semanticObject.getStartDelimeter());
		feeder.accept(grammarAccess.getRuleKeywordToIndexAccess().getEndIndexINTTerminalRuleCall_4_1_0(), semanticObject.getEndIndex());
		feeder.accept(grammarAccess.getRuleKeywordToIndexAccess().getAttrAttributeIDTerminalRuleCall_7_0_1(), semanticObject.getAttr());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID startDelimeter=STRING endDelimeter=STRING attr=[Attribute|ID])
	 */
	protected void sequence_RuleKeyword(EObject context, RuleKeyword semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE__NAME));
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE__ATTR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE__ATTR));
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE_KEYWORD__START_DELIMETER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE_KEYWORD__START_DELIMETER));
			if(transientValues.isValueTransient(semanticObject, S2MPackage.Literals.RULE_KEYWORD__END_DELIMETER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, S2MPackage.Literals.RULE_KEYWORD__END_DELIMETER));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getRuleKeywordAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getRuleKeywordAccess().getStartDelimeterSTRINGTerminalRuleCall_3_1_0(), semanticObject.getStartDelimeter());
		feeder.accept(grammarAccess.getRuleKeywordAccess().getEndDelimeterSTRINGTerminalRuleCall_4_1_0(), semanticObject.getEndDelimeter());
		feeder.accept(grammarAccess.getRuleKeywordAccess().getAttrAttributeIDTerminalRuleCall_7_0_1(), semanticObject.getAttr());
		feeder.finish();
	}
}
