/*
 * generated by Xtext
 */
package org.yazgel.regex.s2m.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class S2MUiModule extends org.yazgel.regex.s2m.ui.AbstractS2MUiModule {
	public S2MUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
