/*
 * generated by Xtext
 */
package org.yazgel.regex.s2m.ui.contentassist

import org.yazgel.regex.s2m.ui.contentassist.AbstractS2MProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class S2MProposalProvider extends AbstractS2MProposalProvider {
}
