/*
 * generated by Xtext
 */
package org.yazgel.regex.s2m.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.yazgel.regex.s2m.services.S2MGrammarAccess;

public class S2MParser extends AbstractContentAssistParser {
	
	@Inject
	private S2MGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.yazgel.regex.s2m.ui.contentassist.antlr.internal.InternalS2MParser createParser() {
		org.yazgel.regex.s2m.ui.contentassist.antlr.internal.InternalS2MParser result = new org.yazgel.regex.s2m.ui.contentassist.antlr.internal.InternalS2MParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getRuleAccess().getAlternatives_3(), "rule__Rule__Alternatives_3");
					put(grammarAccess.getRuleAccess().getAlternatives_4(), "rule__Rule__Alternatives_4");
					put(grammarAccess.getModelAccess().getGroup_0(), "rule__Model__Group_0__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
					put(grammarAccess.getRuleAccess().getGroup_3_0(), "rule__Rule__Group_3_0__0");
					put(grammarAccess.getRuleAccess().getGroup_3_1(), "rule__Rule__Group_3_1__0");
					put(grammarAccess.getRuleAccess().getGroup_4_0(), "rule__Rule__Group_4_0__0");
					put(grammarAccess.getRuleAccess().getGroup_4_1(), "rule__Rule__Group_4_1__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getModelAccess().getNameAssignment_0_2(), "rule__Model__NameAssignment_0_2");
					put(grammarAccess.getModelAccess().getAttributesAssignment_0_4(), "rule__Model__AttributesAssignment_0_4");
					put(grammarAccess.getModelAccess().getRulesAssignment_1(), "rule__Model__RulesAssignment_1");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_5(), "rule__Attribute__TypeAssignment_5");
					put(grammarAccess.getRuleAccess().getNameAssignment_1(), "rule__Rule__NameAssignment_1");
					put(grammarAccess.getRuleAccess().getStartIndexAssignment_3_0_1(), "rule__Rule__StartIndexAssignment_3_0_1");
					put(grammarAccess.getRuleAccess().getStartDelimeterAssignment_3_1_1(), "rule__Rule__StartDelimeterAssignment_3_1_1");
					put(grammarAccess.getRuleAccess().getEndIndexAssignment_4_0_1(), "rule__Rule__EndIndexAssignment_4_0_1");
					put(grammarAccess.getRuleAccess().getEndDelimeterAssignment_4_1_1(), "rule__Rule__EndDelimeterAssignment_4_1_1");
					put(grammarAccess.getRuleAccess().getAttrAssignment_7(), "rule__Rule__AttrAssignment_7");
					put(grammarAccess.getModelAccess().getUnorderedGroup(), "rule__Model__UnorderedGroup");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.yazgel.regex.s2m.ui.contentassist.antlr.internal.InternalS2MParser typedParser = (org.yazgel.regex.s2m.ui.contentassist.antlr.internal.InternalS2MParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public S2MGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(S2MGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
