/*
 * generated by Xtext
 */
package org.yazgel.regex.s2m;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class S2MRuntimeModule extends org.yazgel.regex.s2m.AbstractS2MRuntimeModule {

}
